name: Prod Deploy
on:
  push:
    branches: main

jobs:
  deploy:
    name: Deploy dnd-bot
    runs-on: ubuntu-latest
    steps:
      # This step checks out a copy of your repository.
      - name: Checkout project from git
        uses: actions/checkout@v3
        with:
          repository: dragid10/dnd-bot.git
          ref: main

#       - uses: superfly/flyctl-actions/setup-flyctl@master
#       - run: fly auth docker

      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
#     needs: docker